name = "ctv-api"
main = "worker.js"
compatibility_date = "2024-01-01"

# D1 Database binding
[[d1_databases]]
binding = "DB"
database_name = "vdt"
database_id = "19917e57-ced3-4fc3-adad-368a2e989ea7"

# CORS settings
[vars]
ALLOWED_ORIGINS = "https://your-site.pages.dev,http://localhost:8080"
GOOGLE_APPS_SCRIPT_URL = "https://script.google.com/macros/s/AKfycbxZInEO5xuwHao6t16lxze7vwRoAlYkwGwOdTa5nVFAFgUZLHiltLfeEVu652BZK13h/exec"

# Routes (nếu muốn custom domain)
# routes = [
#   { pattern = "api.yourdomain.com/*", zone_name = "yourdomain.com" }
# ]
